version: "3.8"
services:

  mistral:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3002:8080"
    depends_on:
      - mistral
    restart: unless-stopped

  metabase:
    image: metabase/metabase
    ports:
      - "3001:3000"
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped

  xwiki:
    image: xwiki:lts-mysql-tomcat
    ports:
      - "8081:8080"
    environment:
      - XWIKI_DB_USER=xwiki
      - XWIKI_DB_PASSWORD=xwiki
    restart: unless-stopped

volumes:
  ollama_data:
  metabase_data:
